### ISSUE TITLE
Messed up code

### ISSUE THREAD

**Issue by Hysas** [tobiasitaarnet/ocr-headless#1]
In functions.py there is a serious bug in line 68 where you compare the threshold value to length of text.
The statement "len(text) <= n" is obviously wrong. The exception "Raw extract under threshold value, attempting OCR" then becomes even more frustrating when I kept rerunning the script over and over again with correct threshold just to be notifies that I was under the threshold!

**Comment by tobiasitaarnet** [comment]
Hi Hysas,

If you read the documentation, this was already specified in the example runs:

```bash
# go to OCR if length <= 10, custom output file
python3 main.py -i sample.pdf -n 10 -o test.txt 
```

However, I have updated the `readme` to help people who have reading disabilities. Thanks for making this a more inclusive project! :smiley:
